/**
 * Crossword word lists, curated by article category.
 *
 * Rules for words in this list:
 *   - 3–7 letters only (fits a 7×7 grid comfortably)
 *   - Common enough that a non-specialist can guess from a clue
 *   - No proper nouns (hard to clue fairly)
 *   - No abbreviations
 *   - All uppercase
 *
 * Each category has ~60 words — enough variety that two crosswords
 * from the same category won't feel repetitive.
 */

export type WordEntry = {
  word: string;
  hint: string; // fallback hint if Claude clue generation fails
};

const SCIENCE: WordEntry[] = [
  { word: "ATOM", hint: "Smallest unit of matter" },
  { word: "CELL", hint: "Basic unit of life" },
  { word: "GENE", hint: "Unit of heredity" },
  { word: "LENS", hint: "Focuses light" },
  { word: "MASS", hint: "Measure of matter" },
  { word: "NOVA", hint: "Exploding star" },
  { word: "ORBIT", hint: "Path around a body" },
  { word: "PRISM", hint: "Splits white light" },
  { word: "PULSE", hint: "Rhythmic beat" },
  { word: "QUARK", hint: "Subatomic particle" },
  { word: "SOLAR", hint: "Of the sun" },
  { word: "SPINE", hint: "Backbone" },
  { word: "VAPOR", hint: "Gas from liquid" },
  { word: "VIRUS", hint: "Microscopic pathogen" },
  { word: "ALGAE", hint: "Aquatic plant-like organism" },
  { word: "COMET", hint: "Icy space traveller" },
  { word: "CORAL", hint: "Reef-building marine animal" },
  { word: "DECAY", hint: "Radioactive breakdown" },
  { word: "DELTA", hint: "River mouth formation" },
  { word: "EPOCH", hint: "Geological time period" },
  { word: "FIBER", hint: "Thin strand of material" },
  { word: "FLORA", hint: "Plant life of a region" },
  { word: "FOCAL", hint: "Relating to a focus point" },
  { word: "FUNGI", hint: "Kingdom including mushrooms" },
  { word: "HELIX", hint: "Spiral shape of DNA" },
  { word: "INERT", hint: "Chemically unreactive" },
  { word: "LASER", hint: "Focused light beam" },
  { word: "LUNAR", hint: "Of the moon" },
  { word: "MAGMA", hint: "Molten rock underground" },
  { word: "MERGE", hint: "Combine into one" },
  { word: "NERVE", hint: "Signal-carrying tissue" },
  { word: "OCEAN", hint: "Large body of saltwater" },
  { word: "OZONE", hint: "Atmospheric gas layer" },
  { word: "PHOTO", hint: "Related to light" },
  { word: "PILOT", hint: "Test version of a study" },
  { word: "PLANT", hint: "Photosynthetic organism" },
  { word: "PLATE", hint: "Tectonic section of crust" },
  { word: "POLAR", hint: "Of the poles" },
  { word: "PROBE", hint: "Space exploration craft" },
  { word: "REACT", hint: "Undergo chemical change" },
  { word: "RENAL", hint: "Relating to the kidneys" },
  { word: "RINGS", hint: "Saturn has famous ones" },
  { word: "SERUM", hint: "Blood-derived fluid" },
  { word: "SOLID", hint: "State of matter with fixed shape" },
  { word: "SONIC", hint: "Relating to sound waves" },
  { word: "SPORE", hint: "Reproductive fungal unit" },
  { word: "STEEL", hint: "Iron-carbon alloy" },
  { word: "STORM", hint: "Violent weather system" },
  { word: "SWEEP", hint: "Radar or telescope motion" },
  { word: "TIGER", hint: "Striped big cat" },
  { word: "TIDAL", hint: "Relating to ocean tides" },
  { word: "TOXIN", hint: "Biological poison" },
  { word: "ULTRA", hint: "Beyond normal range" },
  { word: "VENOM", hint: "Injected animal toxin" },
  { word: "VITAL", hint: "Essential for life" },
  { word: "WATER", hint: "H2O" },
  { word: "YIELD", hint: "Amount produced" },
  { word: "ZEBRA", hint: "Striped African mammal" },
  { word: "ZINC", hint: "Metallic element, symbol Zn" },
  { word: "ZONE", hint: "Defined area or region" },
];

const NATURE: WordEntry[] = [
  { word: "BLOOM", hint: "Flower opening" },
  { word: "BROOK", hint: "Small stream" },
  { word: "BURROW", hint: "Animal's underground home" },
  { word: "CANOPY", hint: "Forest roof layer" },
  { word: "CLIFF", hint: "Steep rock face" },
  { word: "CREEK", hint: "Narrow waterway" },
  { word: "DUNE", hint: "Sand hill" },
  { word: "FAUNA", hint: "Animal life of a region" },
  { word: "FERN", hint: "Leafy non-flowering plant" },
  { word: "FIELD", hint: "Open grassy area" },
  { word: "FINCH", hint: "Small seed-eating bird" },
  { word: "FJORD", hint: "Narrow coastal inlet" },
  { word: "FLOOD", hint: "Water overflowing land" },
  { word: "FLOCK", hint: "Group of birds" },
  { word: "FROST", hint: "Ice crystals on surfaces" },
  { word: "GROVE", hint: "Small group of trees" },
  { word: "HAVEN", hint: "Safe refuge" },
  { word: "HERON", hint: "Long-legged wading bird" },
  { word: "HUMID", hint: "Damp atmospheric condition" },
  { word: "KELP", hint: "Large ocean seaweed" },
  { word: "LARCH", hint: "Deciduous conifer" },
  { word: "LEDGE", hint: "Narrow rocky shelf" },
  { word: "LICHEN", hint: "Fungus-algae partnership" },
  { word: "MAPLE", hint: "Syrup-producing tree" },
  { word: "MARSH", hint: "Wetland with grasses" },
  { word: "MIST", hint: "Light fog" },
  { word: "MOOSE", hint: "Largest deer species" },
  { word: "MOSS", hint: "Soft green ground cover" },
  { word: "MOTH", hint: "Nocturnal winged insect" },
  { word: "OTTER", hint: "Aquatic playful mammal" },
  { word: "OWL", hint: "Nocturnal bird of prey" },
  { word: "PETAL", hint: "Flower's coloured leaf" },
  { word: "PINE", hint: "Evergreen conifer" },
  { word: "PLAIN", hint: "Flat open landscape" },
  { word: "POND", hint: "Small body of still water" },
  { word: "POPPY", hint: "Red field flower" },
  { word: "QUAIL", hint: "Small ground-dwelling bird" },
  { word: "RAPID", hint: "Fast-flowing river section" },
  { word: "REEDS", hint: "Tall waterside grasses" },
  { word: "RIDGE", hint: "Narrow hilltop" },
  { word: "RIVER", hint: "Flowing body of water" },
  { word: "ROBIN", hint: "Red-breasted songbird" },
  { word: "ROCKY", hint: "Covered in stones" },
  { word: "ROOTS", hint: "Underground plant anchors" },
  { word: "SEDGE", hint: "Marsh grass plant" },
  { word: "SHADE", hint: "Area blocked from sun" },
  { word: "SLOPE", hint: "Inclined ground surface" },
  { word: "SNAIL", hint: "Shell-carrying mollusc" },
  { word: "SNOWY", hint: "Covered in white flakes" },
  { word: "SOIL", hint: "Earth that plants grow in" },
  { word: "SPINE", hint: "Cactus sharp point" },
  { word: "SPRIG", hint: "Small plant branch" },
  { word: "STORK", hint: "Long-legged migratory bird" },
  { word: "SWIFT", hint: "Fast-flying aerial bird" },
  { word: "THORN", hint: "Sharp plant point" },
  { word: "TRAIL", hint: "Path through wilderness" },
  { word: "TROUT", hint: "Freshwater sport fish" },
  { word: "TULIP", hint: "Spring bulb flower" },
  { word: "VOLE", hint: "Small meadow rodent" },
  { word: "WHALE", hint: "Largest ocean mammal" },
];

const ARTS: WordEntry[] = [
  { word: "ARIA", hint: "Solo operatic song" },
  { word: "BARD", hint: "Poet or storyteller" },
  { word: "BASS", hint: "Low musical register" },
  { word: "BEAT", hint: "Rhythmic musical pulse" },
  { word: "BLUES", hint: "Soulful American music genre" },
  { word: "BRUSH", hint: "Painter's tool" },
  { word: "CANON", hint: "Established artistic works" },
  { word: "CAST", hint: "Group of performers" },
  { word: "CHOIR", hint: "Group of singers" },
  { word: "CHORD", hint: "Multiple notes together" },
  { word: "CLAY", hint: "Sculptor's material" },
  { word: "CRAFT", hint: "Skilled handmade work" },
  { word: "DRAMA", hint: "Theatrical performance genre" },
  { word: "DRIFT", hint: "Narrative direction" },
  { word: "EASEL", hint: "Painter's stand" },
  { word: "ELEGY", hint: "Poem of mourning" },
  { word: "ENVOY", hint: "Closing stanza of a poem" },
  { word: "EPIC", hint: "Grand narrative poem" },
  { word: "ESSAY", hint: "Short analytical piece" },
  { word: "ETUDE", hint: "Musical practice piece" },
  { word: "FABLE", hint: "Moral story with animals" },
  { word: "FLUTE", hint: "Wind instrument" },
  { word: "FOLIO", hint: "Large printed sheet" },
  { word: "FORTE", hint: "One's strong point or loudly" },
  { word: "FRESCO", hint: "Painted onto wet plaster" },
  { word: "GENRE", hint: "Category of artistic work" },
  { word: "GLAZE", hint: "Ceramic surface finish" },
  { word: "GLYPH", hint: "Symbolic carved figure" },
  { word: "HAIKU", hint: "Japanese three-line poem" },
  { word: "HARP", hint: "Stringed concert instrument" },
  { word: "HYMN", hint: "Religious song" },
  { word: "IDIOM", hint: "Figurative expression" },
  { word: "IMAGE", hint: "Visual representation" },
  { word: "IVORY", hint: "Piano key material" },
  { word: "JAZZ", hint: "Improvisational music form" },
  { word: "LUTE", hint: "Medieval stringed instrument" },
  { word: "LYRIC", hint: "Words of a song" },
  { word: "MEDIA", hint: "Artistic materials" },
  { word: "METER", hint: "Poetic rhythm pattern" },
  { word: "MINOR", hint: "Darker musical key" },
  { word: "MURAL", hint: "Wall-painted artwork" },
  { word: "NOVEL", hint: "Long fictional work" },
  { word: "OCTET", hint: "Group of eight performers" },
  { word: "OPERA", hint: "Sung dramatic performance" },
  { word: "PASTEL", hint: "Soft chalk drawing medium" },
  { word: "PAUSE", hint: "Rest in music or speech" },
  { word: "PIANO", hint: "Keyboard instrument" },
  { word: "PITCH", hint: "Musical note frequency" },
  { word: "PLOT", hint: "Story's sequence of events" },
  { word: "POET", hint: "Writer of verse" },
  { word: "PROSE", hint: "Non-verse written form" },
  { word: "QUILL", hint: "Feather writing tool" },
  { word: "RONDO", hint: "Repeating musical form" },
  { word: "SCENE", hint: "Unit of dramatic action" },
  { word: "SCORE", hint: "Written musical notation" },
  { word: "SERIF", hint: "Typeface finishing stroke" },
  { word: "SKETCH", hint: "Rough preliminary drawing" },
  { word: "SONATA", hint: "Instrumental musical form" },
  { word: "STANZA", hint: "Verse paragraph" },
  { word: "TEMPO", hint: "Speed of music" },
  { word: "THEME", hint: "Central artistic idea" },
];

const TECH: WordEntry[] = [
  { word: "ARRAY", hint: "Ordered data structure" },
  { word: "BATCH", hint: "Group processed together" },
  { word: "BINARY", hint: "Base-two number system" },
  { word: "BLOCK", hint: "Unit of stored data" },
  { word: "BOOT", hint: "Start up a system" },
  { word: "BUFFER", hint: "Temporary data storage" },
  { word: "CACHE", hint: "Fast temporary storage" },
  { word: "CHIP", hint: "Integrated circuit" },
  { word: "CLASS", hint: "Object-oriented blueprint" },
  { word: "CLONE", hint: "Exact copy" },
  { word: "CLOUD", hint: "Remote computing platform" },
  { word: "CODEC", hint: "Compression-decompression tool" },
  { word: "CORE", hint: "Processor computing unit" },
  { word: "CRASH", hint: "System failure" },
  { word: "CYCLE", hint: "One processor operation" },
  { word: "DEBUG", hint: "Find and fix code errors" },
  { word: "DRONE", hint: "Unmanned aerial vehicle" },
  { word: "FETCH", hint: "Retrieve from memory" },
  { word: "FIBER", hint: "High-speed cable type" },
  { word: "FLASH", hint: "Non-volatile memory type" },
  { word: "FLOAT", hint: "Decimal number type" },
  { word: "FRAME", hint: "Single video image" },
  { word: "GIANT", hint: "Major tech company" },
  { word: "GRAPH", hint: "Node-edge data structure" },
  { word: "GRID", hint: "Computing resource network" },
  { word: "HASH", hint: "Cryptographic function output" },
  { word: "INDEX", hint: "Database lookup structure" },
  { word: "INPUT", hint: "Data entering a system" },
  { word: "LAYER", hint: "Network protocol level" },
  { word: "LINUX", hint: "Open-source OS kernel" },
  { word: "LOCAL", hint: "On the same machine" },
  { word: "LOGIC", hint: "Boolean reasoning" },
  { word: "LOOP", hint: "Repeating code block" },
  { word: "MACRO", hint: "Automated instruction set" },
  { word: "MERGE", hint: "Combine code branches" },
  { word: "MODAL", hint: "Overlay UI element" },
  { word: "MODEL", hint: "Data representation layer" },
  { word: "MODEM", hint: "Signal modulator device" },
  { word: "MUTEX", hint: "Thread synchronisation lock" },
  { word: "MYSQL", hint: "Popular database system" },
  { word: "PARSE", hint: "Analyse structured text" },
  { word: "PATCH", hint: "Software update fix" },
  { word: "PIXEL", hint: "Smallest screen unit" },
  { word: "PROXY", hint: "Intermediary server" },
  { word: "QUERY", hint: "Database question" },
  { word: "QUEUE", hint: "First-in-first-out structure" },
  { word: "RADAR", hint: "Radio detection system" },
  { word: "RELAY", hint: "Pass signal along chain" },
  { word: "ROUTE", hint: "Network path between nodes" },
  { word: "SCALA", hint: "JVM programming language" },
  { word: "SCOPE", hint: "Variable visibility range" },
  { word: "SHELL", hint: "Command-line interface" },
  { word: "SLICE", hint: "Array sub-section" },
  { word: "SMTP", hint: "Email sending protocol" },
  { word: "STACK", hint: "Last-in-first-out structure" },
  { word: "STATE", hint: "Current system condition" },
  { word: "SURGE", hint: "Sudden power increase" },
  { word: "SWIFT", hint: "Apple's programming language" },
  { word: "SYNC", hint: "Keep data consistent" },
  { word: "TOKEN", hint: "Auth credential unit" },
];

const HEALTH: WordEntry[] = [
  { word: "ACHE", hint: "Dull persistent pain" },
  { word: "ACUTE", hint: "Sudden and severe" },
  { word: "AMINO", hint: "___ acid, protein building block" },
  { word: "AORTA", hint: "Main artery from heart" },
  { word: "AUDIT", hint: "Systematic health review" },
  { word: "BLOOD", hint: "Red circulatory fluid" },
  { word: "BRAIN", hint: "Central nervous organ" },
  { word: "BRISK", hint: "Energetically fast pace" },
  { word: "BURN", hint: "Calorie expenditure" },
  { word: "CALM", hint: "Peaceful mental state" },
  { word: "CARB", hint: "Energy macronutrient" },
  { word: "CHART", hint: "Medical record document" },
  { word: "CLEAN", hint: "Free from toxins" },
  { word: "COMA", hint: "Deep unconscious state" },
  { word: "CORE", hint: "Central body muscles" },
  { word: "COUGH", hint: "Respiratory reflex" },
  { word: "CYCLE", hint: "Exercise machine type" },
  { word: "DETOX", hint: "Remove body toxins" },
  { word: "DIARY", hint: "Food tracking journal" },
  { word: "DOSIS", hint: "Prescribed medication amount" },
  { word: "DOSE", hint: "Prescribed amount of medicine" },
  { word: "DUCT", hint: "Body fluid channel" },
  { word: "ELBOW", hint: "Arm joint" },
  { word: "FAST", hint: "Abstain from eating" },
  { word: "FIBER", hint: "Digestive roughage" },
  { word: "FLORA", hint: "Gut microbiome bacteria" },
  { word: "FLUID", hint: "Body liquid" },
  { word: "GLAND", hint: "Hormone-secreting organ" },
  { word: "GROIN", hint: "Hip-thigh junction area" },
  { word: "HEART", hint: "Cardiac muscle pump" },
  { word: "HERBS", hint: "Natural medicinal plants" },
  { word: "HYDRO", hint: "Water-based therapy prefix" },
  { word: "JOINT", hint: "Bone connection point" },
  { word: "LIVER", hint: "Detoxifying organ" },
  { word: "LOWER", hint: "Beneath the waist" },
  { word: "LUMBAR", hint: "Lower back region" },
  { word: "LYMPH", hint: "Immune system fluid" },
  { word: "NERVE", hint: "Signal-carrying body tissue" },
  { word: "NURSE", hint: "Medical care professional" },
  { word: "PLASM", hint: "Blood liquid component" },
  { word: "PULSE", hint: "Heartbeat rate" },
  { word: "RENAL", hint: "Kidney-related" },
  { word: "REPEL", hint: "Ward off pathogens" },
  { word: "RESET", hint: "Restore body baseline" },
  { word: "REST", hint: "Recovery through sleep" },
  { word: "SALINE", hint: "Salt water solution" },
  { word: "SHINS", hint: "Front lower leg bones" },
  { word: "SLEEP", hint: "Nightly body restoration" },
  { word: "SOLAR", hint: "___ plexus nerve centre" },
  { word: "SPASM", hint: "Involuntary muscle contraction" },
  { word: "SPINE", hint: "Vertebral column" },
  { word: "SPLEEN", hint: "Immune filtering organ" },
  { word: "STEM", hint: "___ cell research" },
  { word: "STING", hint: "Insect venom injection" },
  { word: "STOOL", hint: "Bowel movement sample" },
  { word: "SWEAT", hint: "Cooling body fluid" },
  { word: "TENDON", hint: "Muscle-to-bone connector" },
  { word: "TONIC", hint: "Health-boosting drink" },
  { word: "TOXIN", hint: "Harmful body substance" },
  { word: "VEIN", hint: "Blood return vessel" },
  { word: "VITAL", hint: "___ signs: pulse and BP" },
];

const KINDNESS: WordEntry[] = [
  { word: "ABIDE", hint: "Tolerate with patience" },
  { word: "ADOPT", hint: "Take into one's family" },
  { word: "AGENT", hint: "One who acts for others" },
  { word: "AMITY", hint: "Friendly peaceful relations" },
  { word: "ANGEL", hint: "Heavenly helper figure" },
  { word: "BALM", hint: "Soothing comfort" },
  { word: "BLESS", hint: "Wish well upon someone" },
  { word: "BRAVE", hint: "Courageous in adversity" },
  { word: "BUDDY", hint: "Close companion" },
  { word: "CALM", hint: "Peaceful and reassuring" },
  { word: "CARE", hint: "Look after someone" },
  { word: "CHEER", hint: "Bring joy to others" },
  { word: "CIVIC", hint: "Relating to community duty" },
  { word: "CIVIL", hint: "Polite and respectful" },
  { word: "COACH", hint: "Guide and support" },
  { word: "COMET", hint: "Symbol of hope's arrival" },
  { word: "DONOR", hint: "One who gives freely" },
  { word: "EAGER", hint: "Enthusiastically willing" },
  { word: "EMPATHY", hint: "Sharing another's feelings" },
  { word: "ETHOS", hint: "Community's guiding values" },
  { word: "FAITH", hint: "Trust in others" },
  { word: "FOND", hint: "Warmly affectionate" },
  { word: "FORGE", hint: "Build strong bonds" },
  { word: "FRANK", hint: "Honest and open" },
  { word: "GRACE", hint: "Elegant goodwill" },
  { word: "GRANT", hint: "Give as a gift" },
  { word: "GUIDE", hint: "Help someone find their way" },
  { word: "HAVEN", hint: "Safe welcoming place" },
  { word: "HEART", hint: "Seat of compassion" },
  { word: "HERO", hint: "Selfless brave person" },
  { word: "HONOR", hint: "Respect and esteem" },
  { word: "HOPE", hint: "Optimistic expectation" },
  { word: "HUG", hint: "Comforting embrace" },
  { word: "IDEAL", hint: "Perfect aspiration" },
  { word: "INNER", hint: "From inside oneself" },
  { word: "JOLLY", hint: "Cheerful and friendly" },
  { word: "JOUST", hint: "Champion another's cause" },
  { word: "KARMA", hint: "Good deeds returned" },
  { word: "LEND", hint: "Give temporarily to help" },
  { word: "LIGHT", hint: "Bring clarity to darkness" },
  { word: "LOYAL", hint: "Faithful and devoted" },
  { word: "MERCY", hint: "Compassionate forgiveness" },
  { word: "MIRTH", hint: "Joyful amusement" },
  { word: "MORAL", hint: "Ethically good" },
  { word: "NOBLE", hint: "Morally admirable" },
  { word: "NURSE", hint: "Care tenderly for" },
  { word: "OFFER", hint: "Present for someone's use" },
  { word: "OLIVE", hint: "___ branch, symbol of peace" },
  { word: "PEACE", hint: "Freedom from conflict" },
  { word: "REACH", hint: "Extend help toward someone" },
  { word: "RALLY", hint: "Bring together in support" },
  { word: "SALVE", hint: "Soothing remedy" },
  { word: "SERVE", hint: "Work for others' benefit" },
  { word: "SHARE", hint: "Give a portion to others" },
  { word: "SMILE", hint: "Facial expression of joy" },
  { word: "SPARE", hint: "Give what you can afford" },
  { word: "TRUST", hint: "Confident reliance on someone" },
  { word: "UNITY", hint: "State of being joined" },
  { word: "VALOR", hint: "Great courage" },
  { word: "WARM", hint: "Affectionate and friendly" },
];

const COMMUNITY: WordEntry[] = [
  { word: "ALERT", hint: "Warning to the community" },
  { word: "ANNEX", hint: "Additional building space" },
  { word: "BENCH", hint: "Park or courtroom seat" },
  { word: "BONDS", hint: "Community connections" },
  { word: "BRAVE", hint: "Firefighter's quality" },
  { word: "CAUSE", hint: "Charitable purpose" },
  { word: "CHIEF", hint: "Head of emergency services" },
  { word: "CIVIC", hint: "Relating to citizenship" },
  { word: "CIVIL", hint: "Non-military public service" },
  { word: "CLAIM", hint: "Assert a right" },
  { word: "CLEAN", hint: "Environmental responsibility" },
  { word: "CLERK", hint: "Municipal record keeper" },
  { word: "COAST", hint: "Emergency coastguard area" },
  { word: "CORPS", hint: "Organised service body" },
  { word: "DEPOT", hint: "Emergency vehicle base" },
  { word: "DRAFT", hint: "Initial plan version" },
  { word: "DRILL", hint: "Emergency practice exercise" },
  { word: "ELECT", hint: "Choose by voting" },
  { word: "EQUIP", hint: "Supply with tools" },
  { word: "EVENT", hint: "Community gathering" },
  { word: "FAITH", hint: "Religious community group" },
  { word: "FEAST", hint: "Community shared meal" },
  { word: "FIRST", hint: "___ responder" },
  { word: "FLEET", hint: "Emergency vehicle collection" },
  { word: "FORUM", hint: "Public discussion space" },
  { word: "FRONT", hint: "Community campaign face" },
  { word: "FUNDS", hint: "Charitable money collected" },
  { word: "GRANT", hint: "Government funding award" },
  { word: "GROUP", hint: "Organised community unit" },
  { word: "GUARD", hint: "Protective watch person" },
  { word: "GUILD", hint: "Trade or craft association" },
  { word: "HAUL", hint: "Food bank delivery" },
  { word: "HAVEN", hint: "Community safe house" },
  { word: "HELM", hint: "Leadership position" },
  { word: "HONOR", hint: "Recognition for service" },
  { word: "LEASE", hint: "Community space agreement" },
  { word: "LEVY", hint: "Community tax raised" },
  { word: "LOCAL", hint: "Neighbourhood-based" },
  { word: "LODGE", hint: "Community meeting place" },
  { word: "MARCH", hint: "Peaceful protest walk" },
  { word: "MAYOR", hint: "City's elected leader" },
  { word: "MEDAL", hint: "Service recognition award" },
  { word: "MEDIC", hint: "Emergency healthcare worker" },
  { word: "MERCY", hint: "Charitable compassion" },
  { word: "MURAL", hint: "Community wall artwork" },
  { word: "NEXUS", hint: "Community connection hub" },
  { word: "PANEL", hint: "Advisory community group" },
  { word: "PARK", hint: "Public green space" },
  { word: "PATCH", hint: "Officer's identification badge" },
  { word: "PILOT", hint: "Trial community programme" },
  { word: "PLAZA", hint: "Public gathering square" },
  { word: "RALLY", hint: "Community support gathering" },
  { word: "REACH", hint: "Outreach programme extent" },
  { word: "RELAY", hint: "Charity running event" },
  { word: "RESCUE", hint: "Emergency saving operation" },
  { word: "SAFE", hint: "Protected from harm" },
  { word: "SCOUT", hint: "Youth community organisation" },
  { word: "SQUAD", hint: "Small emergency team" },
  { word: "STAFF", hint: "Organisation's workers" },
  { word: "TRUST", hint: "Charitable foundation" },
  { word: "UNION", hint: "Workers' collective body" },
];

const EDUCATION: WordEntry[] = [
  { word: "ANNEX", hint: "School building addition" },
  { word: "APPLY", hint: "Submit an application" },
  { word: "ATLAS", hint: "Book of maps" },
  { word: "AUDIT", hint: "Academic course review" },
  { word: "AXIOM", hint: "Self-evident mathematical truth" },
  { word: "BADGE", hint: "Achievement recognition" },
  { word: "BOARD", hint: "Surface to write on" },
  { word: "BOOKS", hint: "Primary learning resources" },
  { word: "BRIEF", hint: "Short assignment summary" },
  { word: "CAMPUS", hint: "University grounds" },
  { word: "CHALK", hint: "Blackboard writing tool" },
  { word: "CHART", hint: "Visual data display" },
  { word: "CLASS", hint: "Group of students" },
  { word: "COACH", hint: "Academic mentor" },
  { word: "CRAFT", hint: "Skilled creative subject" },
  { word: "CURVE", hint: "Grade distribution shape" },
  { word: "CYCLE", hint: "Academic year period" },
  { word: "DATUM", hint: "Single data point" },
  { word: "DRAFT", hint: "Early essay version" },
  { word: "DRILL", hint: "Repetition learning method" },
  { word: "ESSAY", hint: "Structured written argument" },
  { word: "EXCEL", hint: "Perform outstandingly" },
  { word: "EXTRA", hint: "Additional credit work" },
  { word: "FACTS", hint: "Verified information" },
  { word: "FIELD", hint: "Subject area of study" },
  { word: "FOCUS", hint: "Concentrated attention" },
  { word: "FORUM", hint: "Academic discussion group" },
  { word: "GLEAN", hint: "Gather knowledge bit by bit" },
  { word: "GRADE", hint: "Academic performance mark" },
  { word: "GRANT", hint: "Academic funding award" },
  { word: "GROUP", hint: "Collaborative study unit" },
  { word: "GUIDE", hint: "Study reference book" },
  { word: "HALLS", hint: "University residence buildings" },
  { word: "INDEX", hint: "Book's alphabetical guide" },
  { word: "INFER", hint: "Draw logical conclusions" },
  { word: "LEARN", hint: "Acquire knowledge" },
  { word: "LEDGE", hint: "Chalk resting place" },
  { word: "LEVEL", hint: "Grade or year of study" },
  { word: "LOGIC", hint: "Reasoning subject" },
  { word: "MAJOR", hint: "Primary university subject" },
  { word: "MARKS", hint: "Scored assessment points" },
  { word: "MERGE", hint: "Combine learning concepts" },
  { word: "MINOR", hint: "Secondary study subject" },
  { word: "MODEL", hint: "Example to follow" },
  { word: "NOVEL", hint: "Long fiction set text" },
  { word: "NOTES", hint: "Recorded lesson points" },
  { word: "PAPER", hint: "Written academic work" },
  { word: "PEERS", hint: "Fellow students" },
  { word: "PILOT", hint: "Trial educational scheme" },
  { word: "PROBE", hint: "Investigate deeply" },
  { word: "PROOF", hint: "Mathematical demonstration" },
  { word: "QUIZ", hint: "Short knowledge test" },
  { word: "QUOTE", hint: "Referenced source text" },
  { word: "READ", hint: "Study written material" },
  { word: "RECAP", hint: "Review previous content" },
  { word: "REFER", hint: "Direct to a source" },
  { word: "RULER", hint: "Straight-edge measuring tool" },
  { word: "SCALE", hint: "Proportional measurement" },
  { word: "SCORE", hint: "Test result total" },
  { word: "STUDY", hint: "Apply oneself to learning" },
  { word: "TEACH", hint: "Impart knowledge" },
];

// ─── Public API ────────────────────────────────────────────────────────────────

export const WORD_BANKS: Record<string, WordEntry[]> = {
  "Science & Discovery":  SCIENCE,
  "Environment & Nature": NATURE,
  "Arts & Culture":       ARTS,
  "Innovation & Tech":    TECH,
  "Health & Wellness":    HEALTH,
  "Human Kindness":       KINDNESS,
  "Community Heroes":     COMMUNITY,
  "Education":            EDUCATION,
};

/** Returns words for a category, or all words combined as fallback */
export function getWordBank(category?: string): WordEntry[] {
  if (category && WORD_BANKS[category]) return WORD_BANKS[category];
  // No category: use all words deduplicated by word text
  const seen = new Set<string>();
  const all: WordEntry[] = [];
  for (const bank of Object.values(WORD_BANKS)) {
    for (const entry of bank) {
      if (!seen.has(entry.word)) {
        seen.add(entry.word);
        all.push(entry);
      }
    }
  }
  return all;
}
